### ISSUE TITLE
Remoção de minions em waves diferentes.

### ISSUE THREAD

**Issue by OdnaropX** [OdnaropX/BCC-2s15-PI6-TowerDefense#5]
Quando mais de uma wave se encontram, alguns elementos da wave anterior são removidos antes que a wave seja finalizada, ou seja, antes que todos os minions da wave anterior cheguem ao destino.

Foi feito teste sem torres.

**Comment by Elindor** [comment]
Não sei se são necessáriamente anteriores, mas vi que alguns próximos ao
centro são removidos.
Uma dupla checagem de posição deve dar certo, mas alem disso, pode dar
merge sim.

Em 4 de dezembro de 2015 00:30, Gabriel notifications@github.com escreveu:

> Quando mais de uma wave se encontram, alguns elementos da wave anterior
> são removidos antes que a wave seja finalizada, ou seja, antes que todos os
> minions da wave anterior cheguem ao destino.
> 
> Foi feito teste sem torres.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OdnaropX/BCC-2s15-PI6-TowerDefense/issues/5.

## 

Atenciosamente,
Gabriel Nopper.

**Comment by OdnaropX** [comment]
Pode deixar que eu corrijo esse bug, acredito que sei o que o causa.
